# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - aptos move compile --named-addresses SwapDeployer=default,Routex=default,ResourceAccountDeployer=default,ResourceAccountDeployer2=default,u256=default,uq64x64=default
    dir:
      ./RouteX
    sources:
      - ./**/*.move
