[package]
name = "amm-v1"
version = "1.0.0"
authors = []

[dev-addresses]

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "bbce0f188d7bef08218f1fc1f46bbd3676b5c74b"}
AptosStdlib = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "bbce0f188d7bef08218f1fc1f46bbd3676b5c74b"}


[dev-dependencies]

[addresses]
std = "0x1"
dev = "cab9a7545a4f4a46308e2ac914a5ce2dcf63482713e683b4bc5fc4b514a790f2"
razor = "65c7939df25c4986b38a6af99602bf17daa1a2d7b53e6847ed25c04f74f54607"
test_coin = "0x16"
