[package]
name = "RoutexV2"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "bbce0f188d7bef08218f1fc1f46bbd3676b5c74b" }
amm-v1 = { local = "../routers/amm-v1" }


[addresses]
Routex = "_"
